name= "luka"
surname= "telia"
print(name + surname)
bithplace="kutaisi"
hometown= "kutaisi"
favourite_travel_destination= "london"
favourite_movie= "coach carter"
least_favourite_movie= "titanic"
country= "georgia"
city= "kutaisi"
love_programming=True
people_who_study_in_goa="Chad"
people_Who_dont_study_in_goa="Virgins"
enjoy_writing=False
enjoy_photography=True
love_cooking=False
favourite_subject="Math"
hobby= "basketball"
enjoy_fishing=True
favourite_book="mze mtvare da puris yana"
favourite_music_genre="rap"
dream_vacation="USA"
favourite_athlete="Michael Jordan"
favourite_animal="dog"
favourite_food= "khinkali"
least_favourite_food= "chijibiji"
name= "luka"
salary= 7500
print(name + "makes" +  str(salary) + "dollars" + "per month")
fitness_routine= "regular workouts"       
favourite athlete = michael jordan
least favourite athlete = cristiano ronaldo 
favourite sport = basketball
least favourite sport = baseball
favourite rapper = tupac
least favourite rapper = snoop dogg
best way to relax = sleep 
enjoy programming = True
favourite subject = math 
least favourite subject = biology
love cooking = false 
least favourite music genre = metal
enjoy writing = false 
enjoy photographing = true 
loves beach = True
loves mountains = True
loves villages = True
least favourite food = chijibiji
favourite animal = dog 
least favourite animal = cat